
export const regions = [
    {
        id:"hokkaido",
        name:"Hokkaido",
        hiragana:"北海道",
        country:"Japan"
    },
    {
        id:"tohoku",
        name:"Tohoku",
        hiragana:"東北",
        country:"Japan"
    },
    {
        id:"chubu",
        name:"Chubu",
        hiragana:"中部",
        country:"Japan"
    },
    {
        id:"kanto",
        name:"Kanto",
        hiragana:"関東",
        country:"Japan"
    },
    {
        id:"kansai",
        name:"Kansai",
        hiragana:"関西",
        country:"Japan"
    },
    {
        id:"chugoku",
        name:"Chugoku",
        hiragana:"中国",
        country:"Japan"
    },
    {
        id:"shikoku",
        name:"Shikoku",
        hiragana:"四国",
        country:"Japan"
    },
    {
        id:"kyushu",
        name:"Kyushu",
        hiragana:"九州",
        country:"Japan"
    }
]

export const prefectures = [
    {
        id:"aichi",
        name:"Aichi",
        hiragana:"愛知",
        region:"Chubu"
    },
    {
        id:"akita",
        name:"Akita",
        hiragana:"秋田",
        region:"Tohoku"
    },
    {
        id:"aomori",
        name:"Aomori",
        hiragana:"青森",
        region:"Tohoku"
    },{
        id:"chiba",
        name:"Chiba",
        hiragana:"千葉",
        region:"Kanto"
    },{
        id:"ehime",
        name:"Ehime",
        hiragana:"愛媛",
        region:"Shikoku"
    },{
        id:"fukui",
        name:"Fukui",
        hiragana:"福井",
        region:"Chubu"
    },{
        id:"fukuoka",
        name:"Fukuoka",
        hiragana:"福岡",
        region:"Kyushu"
    },{
        id:"fukushima",
        name:"Fukushima",
        hiragana:"福島",
        region:"Tohoku"
    },{
        id:"gifu",
        name:"Gifu",
        hiragana:"岐阜",
        region:"Chubu"
    },{
        id:"gunma",
        name:"Gunma",
        hiragana:"群馬",
        region:"Kanto"
    },{
        id:"hiroshima",
        name:"Hiroshima",
        hiragana:"広島",
        region:"Chugoku"
    },{
        id:"hokkaido",
        name:"Hokkaido",
        hiragana:"北海道",
        region:"Hokkaido"
    },{
        id:"hyogo",
        name:"Hyogo",
        hiragana:"兵庫",
        region:"Kansai"
    },{
        id:"ibaraki",
        name:"Ibaraki",
        hiragana:"茨城",
        region:"Kanto"
    },{
        id:"ishikawa",
        name:"Ishikawa",
        hiragana:"石川",
        region:"Chubu"
    },{
        id:"iwate",
        name:"Iwate",
        hiragana:"岩手",
        region:"Tohoku"
    },{
        id:"kagawa",
        name:"Kagawa",
        hiragana:"香川",
        region:"Shikoku"
    },{
        id:"kagoshima",
        name:"Kagoshima",
        hiragana:"鹿児島",
        region:"Kyushu"
    },{
        id:"kanagawa",
        name:"Kanagawa",
        hiragana:"神奈川",
        region:"Kanto"
    },{
        id:"kochi",
        name:"Kochi",
        hiragana:"高知",
        region:"Shikoku"
    },{
        id:"kumamoto",
        name:"Kumamoto",
        hiragana:"熊本",
        region:"Kyushu"
    },{
        id:"kyoto",
        name:"Kyoto",
        hiragana:"京都府",
        region:"Kansai"
    },{
        id:"mie",
        name:"Mie",
        hiragana:"三重",
        region:"Kansai"
    },{
        id:"miyagi",
        name:"Miyagi",
        hiragana:"宮城",
        region:"Tohoku"
    },{
        id:"miyazaki",
        name:"Miyazaki",
        hiragana:"宮崎",
        region:"Kyushu"
    },{
        id:"nagano",
        name:"Nagano",
        hiragana:"長野",
        region:"Chubu"
    },{
        id:"nagasaki",
        name:"Nagasaki",
        hiragana:"長崎",
        region:"Kyushu"
    },{
        id:"nara",
        name:"Nara",
        hiragana:"奈良",
        region:"Kansai"
    },{
        id:"niigata",
        name:"Niigata",
        hiragana:"新潟",
        region:"Chubu"
    },{
        id:"oita",
        name:"Oita",
        hiragana:"大分",
        region:"Kyushu"
    },{
        id:"okayama",
        name:"Okayama",
        hiragana:"岡山",
        region:"Chugoku"
    },{
        id:"okinawa",
        name:"Okinawa",
        hiragana:"沖縄",
        region:"Kyushu"
    },{
        id:"osaka",
        name:"Osaka",
        hiragana:"大阪",
        region:"Kansai"
    },{
        id:"saga",
        name:"Saga",
        hiragana:"佐賀",
        region:"Kyushu"
    },{
        id:"saitama",
        name:"Saitama",
        hiragana:"埼玉",
        region:"Kanto"
    },{
        id:"shiga",
        name:"Shiga",
        hiragana:"滋賀",
        region:"Kansai"
    },{
        id:"shimane",
        name:"Shimane",
        hiragana:"島根",
        region:"Chugoku"
    },{
        id:"shizuoka",
        name:"Shizuoka",
        hiragana:"静岡",
        region:"Chubu"
    },{
        id:"tochigi",
        name:"Tochigi",
        hiragana:"栃木",
        region:"Kanto"
    },{
        id:"tokushima",
        name:"Tokushima",
        hiragana:"徳島",
        region:"Shikoku"
    },{
        id:"tokyo",
        name:"Tokyo",
        hiragana:"東京",
        region:"Kanto"
    },{
        id:"tottori",
        name:"Tottori",
        hiragana:"鳥取",
        region:"Chugoku"
    },{
        id:"toyama",
        name:"Toyama",
        hiragana:"富山",
        region:"Chubu"
    },{
        id:"wakayama",
        name:"Wakayama",
        hiragana:"和歌山",
        region:"Kansai"
    },{
        id:"yamagata",
        name:"Yamagata",
        hiragana:"山形",
        region:"Tohoku"
    },{
        id:"yamaguchi",
        name:"Yamaguchi",
        hiragana:"山口",
        region:"Chugoku"
    },{
        id:"yamanashi",
        name:"Yamanashi",
        hiragana:"山梨",
        region:"Chubu"
    }
    
]