
export const regions = [
    {
        id:"Hokkaido",
        name:"Hokkaido",
        hiragana:"北海道",
        country:"Japan"
    },
    {
        id:"Tohoku",
        name:"Tohoku",
        hiragana:"東北",
        country:"Japan"
    },
    {
        id:"Chubu",
        name:"Chubu",
        hiragana:"中部",
        country:"Japan"
    },
    {
        id:"Kanto",
        name:"Kanto",
        hiragana:"関東",
        country:"Japan"
    },
    {
        id:"Kansai",
        name:"Kansai",
        hiragana:"関西",
        country:"Japan"
    },
    {
        id:"Chugoku",
        name:"Chugoku",
        hiragana:"中国",
        country:"Japan"
    },
    {
        id:"Shikoku",
        name:"Shikoku",
        hiragana:"四国",
        country:"Japan"
    },
    {
        id:"Kyushu",
        name:"Kyushu",
        hiragana:"九州",
        country:"Japan"
    }
]

export const prefectures = [
    {
        id:"Aichi",
        name:"Aichi",
        hiragana:"愛知",
        region:"Chubu"
    },
    {
        id:"Akita",
        name:"Akita",
        hiragana:"秋田",
        region:"Tohoku"
    },
    {
        id:"Aomori",
        name:"Aomori",
        hiragana:"青森",
        region:"Tohoku"
    },{
        id:"Chiba",
        name:"Chiba",
        hiragana:"千葉",
        region:"Kanto"
    },{
        id:"Ehime",
        name:"Ehime",
        hiragana:"愛媛",
        region:"Shikoku"
    },{
        id:"Fukui",
        name:"Fukui",
        hiragana:"福井",
        region:"Chubu"
    },{
        id:"Fukuoka",
        name:"Fukuoka",
        hiragana:"福岡",
        region:"Kyushu"
    },{
        id:"Fukushima",
        name:"Fukushima",
        hiragana:"福島",
        region:"Tohoku"
    },{
        id:"Gifu",
        name:"Gifu",
        hiragana:"岐阜",
        region:"Chubu"
    },{
        id:"Gunma",
        name:"Gunma",
        hiragana:"群馬",
        region:"Kanto"
    },{
        id:"Hiroshima",
        name:"Hiroshima",
        hiragana:"広島",
        region:"Chugoku"
    },{
        id:"Hokkaido",
        name:"Hokkaido",
        hiragana:"北海道",
        region:"Hokkaido"
    },{
        id:"Hyogo",
        name:"Hyogo",
        hiragana:"兵庫",
        region:"Kansai"
    },{
        id:"Ibaraki",
        name:"Ibaraki",
        hiragana:"茨城",
        region:"Kanto"
    },{
        id:"Ishikawa",
        name:"Ishikawa",
        hiragana:"石川",
        region:"Chubu"
    },{
        id:"Iwate",
        name:"Iwate",
        hiragana:"岩手",
        region:"Tohoku"
    },{
        id:"Kagawa",
        name:"Kagawa",
        hiragana:"香川",
        region:"Shikoku"
    },{
        id:"Kagoshima",
        name:"Kagoshima",
        hiragana:"鹿児島",
        region:"Kyushu"
    },{
        id:"Kanagawa",
        name:"Kanagawa",
        hiragana:"神奈川",
        region:"Kanto"
    },{
        id:"Kochi",
        name:"Kochi",
        hiragana:"高知",
        region:"Shikoku"
    },{
        id:"Kumamoto",
        name:"Kumamoto",
        hiragana:"熊本",
        region:"Kyushu"
    },{
        id:"Kyoto",
        name:"Kyoto",
        hiragana:"京都府",
        region:"Kansai"
    },{
        id:"Mie",
        name:"Mie",
        hiragana:"三重",
        region:"Kansai"
    },{
        id:"Miyagi",
        name:"Miyagi",
        hiragana:"宮城",
        region:"Tohoku"
    },{
        id:"Miyazaki",
        name:"Miyazaki",
        hiragana:"宮崎",
        region:"Kyushu"
    },{
        id:"Nagano",
        name:"Nagano",
        hiragana:"長野",
        region:"Chubu"
    },{
        id:"Nagasaki",
        name:"Nagasaki",
        hiragana:"長崎",
        region:"Kyushu"
    },{
        id:"Nara",
        name:"Nara",
        hiragana:"奈良",
        region:"Kansai"
    },{
        id:"Niigata",
        name:"Niigata",
        hiragana:"新潟",
        region:"Chubu"
    },{
        id:"Oita",
        name:"Oita",
        hiragana:"大分",
        region:"Kyushu"
    },{
        id:"Okayama",
        name:"Okayama",
        hiragana:"岡山",
        region:"Chugoku"
    },{
        id:"Okinawa",
        name:"Okinawa",
        hiragana:"沖縄",
        region:"Kyushu"
    },{
        id:"Osaka",
        name:"Osaka",
        hiragana:"大阪",
        region:"Kansai"
    },{
        id:"Saga",
        name:"Saga",
        hiragana:"佐賀",
        region:"Kyushu"
    },{
        id:"Saitama",
        name:"Saitama",
        hiragana:"埼玉",
        region:"Kanto"
    },{
        id:"Shiga",
        name:"Shiga",
        hiragana:"滋賀",
        region:"Kansai"
    },{
        id:"Shimane",
        name:"Shimane",
        hiragana:"島根",
        region:"Chugoku"
    },{
        id:"Shizuoka",
        name:"Shizuoka",
        hiragana:"静岡",
        region:"Chubu"
    },{
        id:"Tochigi",
        name:"Tochigi",
        hiragana:"栃木",
        region:"Kanto"
    },{
        id:"Tokushima",
        name:"Tokushima",
        hiragana:"徳島",
        region:"Shikoku"
    },{
        id:"Tokyo",
        name:"Tokyo",
        hiragana:"東京",
        region:"Kanto"
    },{
        id:"Tottori",
        name:"Tottori",
        hiragana:"鳥取",
        region:"Chugoku"
    },{
        id:"Toyama",
        name:"Toyama",
        hiragana:"富山",
        region:"Chubu"
    },{
        id:"Wakayama",
        name:"Wakayama",
        hiragana:"和歌山",
        region:"Kansai"
    },{
        id:"Yamagata",
        name:"Yamagata",
        hiragana:"山形",
        region:"Tohoku"
    },{
        id:"Yamaguchi",
        name:"Yamaguchi",
        hiragana:"山口",
        region:"Chugoku"
    },{
        id:"Yamanashi",
        name:"Yamanashi",
        hiragana:"山梨",
        region:"Chubu"
    }
    
]